ithaka/aiw-ui

src/app/shared/auth.service.ts

Cleaning up logic for handling expired sessions. We should be showing the modal in the following cases:
- Auth service returning a user as logged out because tokens expired
- Our app timing out after 60min
- Cookies being cleared and the app trying to refresh the user
I've added a loggedInSessionLost flag to the user object so this handled consistently

Save a "loggedInSessionLost" flag

---

src/app/login/login.component.pug
src/app/login/login.component.ts
src/app/modals/add-to-group/add-to-group.component.pug
src/app/modals/add-to-group/add-to-group.component.ts

Fixes keyboard nav for autocomplete on:
- Institutional log in dropdown
- Add to group dropdown of groups

Air 1711: Keyboard nav of autocomplete

---

src/app/shared/auth.service.ts
src/app/white-label-config.ts

+ Additional check for variable added to the other condition that saves the user object

AIR-1691: Sahara redirect should use "isOpenAccess" on config

---

src/app/browse-page/card-view/card-view.component.ts

Show Image Group as Shared with Me When the Logged In User is Not the Owner of the Group

AIR-1417-fix

---

README.md
config/webpack.dev.js
config/webpack.prod.js
config/webpack.test.js
src/app/pact/group-api.pact.spec.ts
src/app/shared/group.service.ts
src/custom-typings.d.ts

- The beginnings of using environment variables
- Fix for running Pact tests

Air pact fix

---

src/app/asset-page/asset-page.component.ts
src/app/shared/script.store.ts

We're no longer using the third party crazyegg heat map service

Remove crazyegg script references

---

src/app/browse-page/browse-groups/groups.component.pug
src/assets/i18n/en.json

Update to interface based on changes made to the groups call api

Change level from 'private' to 'created'

---

src/app/browse-page/browse-groups/tags-list.component.ts
src/app/browse-page/card-view/card-view.component.ts

- Make sure applying and clearing tags from pages >= 2 should land the user on page 1 to show results

AIR-1769 (Applying and clearing tags from page 2 doesn't land on page 1)

---

src/app/browse-page/browse-groups/groups.component.pug

Make sure we return to page 1 if we do a search in page larger than 1.

AIR-1781: Image Group Search: Return to Page 1 When Search

---

src/app/browse-page/browse-groups/groups.component.pug
src/app/browse-page/browse-groups/groups.component.ts

AIR-1718 (Remove image groups card view flag)

---

src/app/browse-page/browse-groups/groups.component.ts

GroupSearch.cleanSearchTerm needed all instances of '/' replaced

AIR-1779 PR#2

---

src/app/browse-page/browse-groups/groups.component.ts
src/app/browse-page/card-view/card-view.component.pug

Make sentence casing consistent

AIR-1790 (Sentence Casing within Image Groups "groups" filter)

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.ts
src/app/asset-filters/asset-filters.service.ts
src/app/shared/asset-search.service.ts
src/assets/i18n/en.json

Reverts ithaka/aiw-ui#622
We are reverting this merge and putting 1183 on hold in AIR-1183 branch... to be continued.

Revert "Air-1183 (Handle accessibility on search results page)"

---

src/app/asset-grid/asset-grid.component.ts
src/app/asset-page/asset-page.component.ts

Reverts ithaka/aiw-ui#630
Need to debug console error, reverting previous merge.

Revert "Air-1799"

---

src/app/login/login.component.ts

Revert "AIR-1791"

---

src/app/collection-page/collection-page.component.ts
src/app/home/home.component.ts
src/app/search-page/search-page.component.ts
src/app/shared/script.service.ts
src/app/shared/script.store.ts

Added to:
Home page
Search page
Collection page

Ethnio: Add compound object survey

---

src/app/collection-page/collection-page.component.pug
src/app/pcollection-page/pcollection-page.component.pug

Binder is now returning a full url for "bigimageurl"

Collection Thumb: Use as full url

---

package.json
src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/shared/flag.service.ts
src/app/shared/metadata.service.ts
yarn.lock

+ Flag service for country roll out
+ "featureFlag=solrMetadata" on asset page

AIR-1764: solrMetadata feature flag

---

src/app/browse-page/browse-page.component.scss

- Make the selection of collection, classification, and geography bold when it's active.

AIR-1862 (Collection browse: bold selection)

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/thumbnail/thumbnail.component.pug
src/app/asset-grid/thumbnail/thumbnail.component.ts
src/app/search-page/search-page.component.pug

- Change the alt text of the image in thumbnail.
- Change the tabIndex so that we only focus on the image, not the whole thumbnail (because VoiceOver will read everything in a thumbnail if we focus on the whole, and the information will be read twice).
- Currently the VoiceOver will not read anything below the nav menu. The problem is supposed to be solved in another ticket. But we can test it by adding a .div to wrap up the nav and the main-content of search page component template (this method temporarily solve the VoiceOver problem).
Note: the exact message to show when there is no title or no creator is not fully determined. Kelsey will create another ticket for that.

AIR-1865 (Append creator to alt text)

---

package-lock.json
package.json
src/app/asset-page/asset-page.component.ts
src/sass/app.scss
src/sass/modules/_icons.scss
src/sass/modules/_viewer.scss
yarn.lock

Search by id for example assets:
SSID.              Artstor Id 
1002229135   SS35494_35494_39174389
1002387701   SS35494_35494_39230723
1002547028  SS34216_34216_39230202
Added:
- Show reference strip along bottom of viewer
- Show arrows on left and right of viewer to paginate
- Show pagination values above reference strip
- Handle data format for multi views (not visible to user)
- Add explanation/help modal for multi views

Air 1393: Multi-View Support

---

package.json
src/sass/modules/_viewer.scss
yarn.lock

- Thumbnails display on multi views
- Navigator is positioned in bottom left correctly

Air 1911: Thumbnail and navigator fixes

---

src/app/search-page/search-page.component.ts

- Make sure user object is fresh before we search.

AIR-1909 (Coming from JSTOR to Artstor server error)

---

src/app/asset-grid/thumbnail/thumbnail.component.pug
src/app/asset-grid/thumbnail/thumbnail.component.ts
src/app/browse-page/card-view/card-view.component.pug
src/app/browse-page/card-view/card-view.component.ts
src/app/modals/share-link-modal/share-link-modal.component.pug
src/app/shared/asset-search.service.ts
src/app/shared/auth.service.ts

- Show Multi-view items for thumbnail, image group cardview, and generate share link modal

AIR-1927 (Multi-view item thumbnail not displaying)

---

src/app/shared/assets.service.ts

Revert "Air 1803"

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts

- Add GA tracking to select image to compare action
- Event action: Compare image
- Label: number of assets being compared

AIR-1820 (Add tracking to comparison mode)

---

package.json

Yarn install ng-artstor-viewer v1.3.2

Publish viewer for 1925 styles

---

src/app/app.component.ts

Wrap the skip-to-main-content link and nav bar with a div to enbale screen reader to read the whole page.

AIR-1963 (Screenreader not reading below nav)

---

src/app/image-group-page/image-group-page.component.ts

We have this.user to avoid calling this._auth.getUser() every time we need user info, but it looks like we missed one. So I change from using this._auth.getUser() to this.user and check that this.user.institutionId exists so we can call toString() to it.

Air-1797 (Fix error for undefined is not an object in Image Group component)

---

src/app/shared/tour/tour.component.pug
src/app/shared/tour/tour.component.ts
src/sass/modules/_tour.scss

- Get the styles back
- Align the page properly during tour

Air-1965 (Fix image group tour)

---

src/app/modals/search-modal/search-modal.component.pug
src/app/modals/search-modal/search-modal.component.ts

- Check the last button's tab keydown event, close the dropdown on that

AIR-1930 (Close dropdown with tabbing on Advanced Search Modal (Add Any Field))

---

src/assets/i18n/en.json

en.json typo fix

---

src/app/browse-page/tag/tag.component.pug

- Make Edit button in personal collection page focusable and have correct label

AIR-1971 (Add and create labels for Personal Collections)

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.ts

- Remove feature flag for contributor filter
- Limit the number of filters to be 17 max

Air-1856 (Remove contribFilter featureFlag)

---

src/sass/app.scss
yarn.lock

Simple display override when app is in fullscreen

AIR-1885: Hide Ethnio screener in fullscreen

---

src/app/register/register.component.pug

- Wrap the template with a div to enable VoiceOver
- Add aria labels

AIR-1961 (Add and create labels on register page)

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.ts
src/app/shared/asset-search.service.ts
src/assets/i18n/en.json

Reverts ithaka/aiw-ui#804
NOTE: Reverting for deployment

Revert "AIR-2007"

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.ts
src/app/shared/asset-search.service.ts
src/assets/i18n/en.json

Re-merge AIR-2007 changes for test

---

package.json
yarn.lock

- Effectively disable "lazy loading" on Multi View thumbnail strip, so all load

AIR-1980: Multi-view thumbs (load all)

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.ts
src/app/shared/asset-search.service.ts
src/assets/i18n/en.json

Reverts ithaka/aiw-ui#810
NOTE: Moving this feature to test branch named `donating-contribs-master` to keep master branch stable for deployments until this story has test approval.

Revert "Re-merge AIR-2007 changes for test"

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.ts
src/app/shared/asset-search.service.ts
src/assets/i18n/en.json

Re-Merge "AIR-2007""

---

src/app/browse-page/card-view/card-view.component.ts
src/app/shared/asset-search.service.ts
src/app/shared/assets.service.ts
src/app/shared/auth.service.ts
src/environments/environment.prod.ts
src/environments/environment.ts

@codiak PR 1 of AIR-2070
Use environment to set and use stor stage url

Multiview thumbnails: use stage stor url in test environment

---

src/app/category-page/category-page.component.ts
src/app/shared/assets.service.ts

+ Also cleaned up where we were making the categorydesc call

Air 2040: Content Unavailable modal for Category 403s

---

src/app/register/register.component.ts

Register: handle logged in user route from register

AIR-2041 follow up

---

src/app/modals/search-modal/search-modal.component.pug
src/app/modals/search-modal/search-modal.component.ts

+ Cleaned out deprecated collection list code
+ Fix pre-filling with existing applied filters

AIR-2042 Adv Search: fix pre-filling

---

package.json
yarn.lock

AIR-2002 [yarn install] Viewer update fix CPU leak

---

src/app/browse-page/browse-page.component.scss
src/app/browse-page/my-collections.component.pug
src/app/browse-page/my-collections.component.ts
src/app/browse-page/tag/tag.component.pug
src/app/browse-page/tags.service.ts
src/app/pcollection-page/pcollection-page.component.ts

This feature work is mostly complete, may need some additional clean out of unused code, but opening PR to get some eyes on it.

Air 2080: Implement My Collections using new endpoint

---

src/app/asset-page/asset-page.component.ts
src/app/modals/add-to-group/add-to-group.component.ts
src/app/shared/tour/tour.component.ts

- Enables Tour code on client
- Fix private/public member errors

Stage update

---

src/app/modals/add-to-group/add-to-group.component.ts
src/assets/i18n/en.json

AIR-596 & AIR-2094

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.ts
src/app/asset-page/asset-page.component.ts
src/app/shared/datatypes/asset.interface.ts
src/sass/modules/_buttons.scss

+ Handle downloading "single views"
+ Display "single views" as regular images

Air 2138: Handle "single view" multi views

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.scss
src/app/asset-filters/asset-filters.component.ts
src/app/shared/institutions.service.ts

- Replace the nested subscription with two independent subscription. Make sure we assign available filters only when we have both institution result and filters result.
- Add loading icon when the filters are not loaded.

AIR-2133 (Add a loading icon for filter pane on search results page)

---

src/app/asset-page/asset-page.component.pug
src/assets/i18n/en.json

Updating the term image -> item in the error message on add to existing group modal and changing the download dropdown menu item to sentence case.

Small update to terms

---

src/app/asset-grid/asset-grid.component.ts

AIR-2147-follow up

---

src/app/modals/add-to-group/add-to-group.component.pug
src/app/modals/add-to-group/add-to-group.component.ts

Update Add to Group tabbing functions to handle shift tab from Add button when a selection is made
Also add click event detection to the selection logic to be same as Space orEnter on a group

AIR-2090-2

---

src/app/_services/metadata.service.ts
src/app/asset-pp-page/asset-pp-page.component.ts
src/app/browse-page/card-view/card-view.component.pug
src/app/shared/asset-search.service.ts

- The print preview page's problem is not limited to downgraded multi-view, it is not loading for all multi-view.

AIR-2140 (Asset thumbnails (downgraded from Multiview) not displaying on print preview, groups page)

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.scss
src/app/asset-grid/asset-grid.component.ts

- Change from "opacity: 0" to "display: none" to make it really disappear instead of just hidden
- Set another variable "animationFinished" that are set to be true 400 ms (the time of the animation) after setting showIgDescBool to be true

AIR-2147-fix

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts

Asset Grid: add showGroupDetails for initial state of no tags or description

2147 Details Display Fix

---

src/app/asset-grid/thumbnail/thumbnail.component.pug

Thumb comp: pass new bool to makeThumbUrl for MV in reorder mode

2140 Multiview Thumbnail fix when in reorder mode

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts
src/app/shared/asset-search.service.ts

- Avoiding using a function that's constantly re-evaluated in template
- "igDisplay" var set by setter cleans up some of our conditional logic
- Ensure non-group pages display cleanly

Asset Grid: Clean up IG Details variable usage

---

src/app/browse-page/tags.service.ts
src/app/shared/assets.service.ts
src/app/shared/image-group.service.ts

Found while listing endpoints for https://wiki.jstor.org/plugins/servlet/samlsso?redirectTo=%2Fpages%2Fviewpage.action%3FpageId%3D222076662

Service cleaning: Remove unused calls

---

src/app/app.module.ts
src/app/image-group-page/image-group-page.component.pug
src/app/shared/group-title/group-title.component.pug
src/app/shared/group-title/group-title.component.scss
src/app/shared/group-title/group-title.component.ts
src/app/shared/index.ts
src/sass/core/_layout.scss

- A "group-title" component contains new style
- Change only appearing on image group for now
- Public css change of search bar with larger margin according to Kelsey
- Two pseudo-elements for the full-width borders
- The "Export" and "Present" buttons are just placeholders for now

AIR-2141 (Update Image Group Page "Header")

---

src/app/asset-grid/thumbnail/thumbnail.component.pug

Revert "2164-fix Badge / Icon layout in downgraded media icon conditional"

---

src/app/asset-grid/thumbnail/thumbnail.component.pug
src/app/asset-grid/thumbnail/thumbnail.component.ts
src/app/shared/datatypes/thumbnail.interface.ts

Thumbnail interface: add format to media object
Thumbnail Comp: Add isDowngradedMedia bool to simplify template logic

2164 - Fix isDowngraded icon conditional

---

src/app/login-form/login-form.component.ts
src/assets/i18n/en.json

- Check for error code 422 for lost password
- Update error message for lost password
Note: the message in the response seems to have NOT been decided by Auth team. It may be easier for us to check the response message later?

AIR-2166 (AIW and Admin: New error code for passwords we can't match)

---

src/app/asset-filters/asset-filters.component.pug
src/app/asset-filters/asset-filters.component.ts

- Assign correct count to collection type filters so that the collection type filter is not empty
- Remove filter if there is only one facet in it and the only facet's name is empty

AIR-2056 (Collection type filter is empty on search page for some institutional collections)

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.scss
src/app/asset-page/artstor-viewer/artstor-viewer.component.ts
src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/shared/datatypes/asset.interface.ts

Saved views support in fullscreen mode
Fullscreen images aren't being centered vertically in fullscreen while comparing
Compare mode issue fixes.

AIR-2161 & AIR-2058

---

src/app/nav-menu/nav-menu.component.pug
src/app/nav-menu/nav-menu.component.ts
src/assets/i18n/en.json

- Add "Export Group to Powerpoint" and "Export Group as a ZIP" to "Share" dropdown menu
- Behind feature flag "featureFlag=exportReframe"
Note: The "G" of group is capitalized to be consistent with other items

AIR-2126 (Add export options to "Share" dropdown menu)

---

package.json
src/app/image-group-page/ig-download-modal/ig-download-modal.component.ts
src/app/shared/assets.service.ts
src/app/shared/group.service.ts

Fixes for group changes:
- Download/export
- Share link generation
- Print preview

Air 1810 Fast Follow: Fix download, print preview and share

---

src/app/asset-grid/thumbnail/thumbnail.component.ts

Thumbnail Comp: Verify compound_media field length in conditional for determining isMultiView

2212-from-master

---

src/app/app.component.ts
src/app/app.module.ts
src/app/asset-filters/asset-filters.component.ts
src/app/asset-grid/asset-grid.component.ts
src/app/asset-grid/thumbnail/thumbnail.component.ts
src/app/asset-page/asset-page.component.ts
src/app/browse-page/browse-groups/groups.component.ts
src/app/image-group-page/ig-download-modal/ig-download-modal.component.ts
src/app/login-form/login-form.component.ts
src/app/modals/add-to-group-legacy/add-to-group-legacy.component.ts
src/app/modals/add-to-group/add-to-group.component.ts
src/app/modals/new-ig-modal/new-ig-modal.component.ts
src/app/modals/search-modal/search-modal.component.ts
src/app/register/register.component.ts
src/app/search-page/prompt/prompt.component.ts
src/app/shared/auth.service.ts
src/app/shared/search/search.component.ts
src/app/shared/tour/tour.component.ts
src/index.html

- Track existing events via Google Tag Manager

Air 2170: Use Google Tag Manager

---

src/app/app.component.ts
src/app/asset-filters/asset-filters.component.ts
src/app/asset-page/asset-page.component.ts
src/app/shared/auth.service.ts
src/app/shared/search/search.component.ts

Be sure to read the jira ticket, and test with either the extension or Tag Manager

Air 2171: GTM Data layer variable tracking

---

src/app/asset-page/asset-page.component.pug

- Disable add detail to group when viewer doesn't load

AIR-2218 (Disable add detail if viewer doesn't load)

---

src/app/register/register.component.pug
src/app/register/register.component.ts
src/assets/i18n/en.json

- Check for new status message for this specific case 
- Display message explaining the situation to the user, and how they can continue

Register: Display appropriate message for Google/Jstor users

---

src/app/app.component.ts
src/app/asset-filters/asset-filters.component.ts
src/app/asset-grid/asset-grid.component.ts
src/app/asset-page/asset-page.component.ts
src/app/browse-page/browse-groups/groups.component.ts
src/app/image-group-page/ig-download-modal/ig-download-modal.component.ts
src/app/login-form/login-form.component.ts
src/app/modals/add-to-group-legacy/add-to-group-legacy.component.ts
src/app/modals/add-to-group/add-to-group.component.ts
src/app/modals/new-ig-modal/new-ig-modal.component.ts
src/app/modals/search-modal/search-modal.component.ts
src/app/register/register.component.ts
src/app/search-page/prompt/prompt.component.ts
src/app/shared/auth.service.ts
src/app/shared/search/search.component.ts
src/app/shared/tour/tour.component.ts

Fixes the following:
- browse page names tracked correctly
- categories should be updated (no longer user login type)
- track in trackContentDataLayer() bug fix ("Classification" error)

Air 2171: GTM fast follow fixes

---

src/app/image-group-page/ig-download-modal/ig-download-modal.component.ts
src/app/modals/add-to-group-legacy/add-to-group-legacy.component.ts
src/app/shared/group.service.ts

+ Catch "null" values from download service
+ 2x Error handling for PUT/POST situation

Air 2191: Unique session expired cases

---

src/app/_services/metadata.service.ts
src/app/asset-page/asset-page.component.pug

- Better failure handling if /imagefpx does not load
- Show "Add to group" for all assets

AIR-2153 follow up

---

src/app/login-form/login-form.component.ts
src/app/login/login.component.pug
src/app/login/login.component.ts
src/app/modals/pwd-reset/pwd-reset.component.pug
src/app/modals/pwd-reset/pwd-reset.component.ts
src/assets/i18n/en.json
src/sass/core/_typography.scss
src/sass/modules/_forms.scss
src/sass/modules/_modals.scss

You can test with :
qatester@artstor.org / artstor
BUT DO NOT RESET THE PASSWORD!!!!!!!

Air 2240: Ghost reset modal

---

src/assets/i18n/en.json
src/sass/modules/_modals.scss

- On create new image group modal: Change "add item to existing group" to be "add to existing group"

AIR-2194 (Quick fix: Change "add item to existing group" to be "add to existing group")

---

src/app/modals/new-ig-modal/new-ig-modal.component.pug
src/sass/modules/_modals.scss

The footer style of new image group is a little different with others. Update it to be more consistent, so that we have same margin and padding.

AIR-2194 fix

---

src/app/modals/pwd-reset/pwd-reset.component.pug
src/app/modals/pwd-reset/pwd-reset.component.ts

Reverts ithaka/aiw-ui#948 To fix prod build

Revert "Air 2242"

---

src/app/browse-page/browse-page.component.scss
src/app/modals/google-auth/google-auth.component.pug
src/assets/i18n/en.json
src/sass/modules/_filters.scss

A couple nice little CSS tweaks

Air design refine 003

---

src/app/shared/group-title/group-title.component.scss

- CSS change according to Kelsey.

AIR-2189 (Export dropdown: design fixes)

---

src/app/asset-grid/thumbnail/thumbnail.component.pug
src/app/asset-grid/thumbnail/thumbnail.component.ts

Thumbnail Comp: Add conditions for Detail Views that are also Downgraded Media

AIR-2283(Thumbnails for detailed views of downgraded multi view images are not loading in the group)

---

server/server.ts

**NOTE:**
@codiak  Let's test this to see if I've covered our basis here, or if we need a more thorough approach to disallow methods.

Server: disallow put and post - let's test

---

src/app/app.module.ts
src/app/app.routes.ts
src/app/shared/asset-search.service.ts
src/app/ssid-mapping/index.ts
src/app/ssid-mapping/ssid-mapping.component.pug
src/app/ssid-mapping/ssid-mapping.component.scss
src/app/ssid-mapping/ssid-mapping.component.ts

AIR-2224: SSID route

---

src/app/modals/new-ig-modal/new-ig-modal.component.pug
src/app/modals/new-ig-modal/new-ig-modal.component.ts
src/assets/i18n/en.json
src/sass/modules/_modals.scss

- Prevent background tabbing for Edit group modal 
- Change the button text in the modal from "Close" to "Cancel"

Air 2148 b: Edit group modal tweaks

---

src/app/image-group-page/image-group-page.component.pug
src/app/image-group-page/image-group-page.component.ts
src/app/modals/loading-state/loading-state.component.pug
src/app/modals/loading-state/loading-state.component.ts

- Add triggerRetry output for Try again link
- Don't show progress bar on error state
- rename handleTC.. to exportGroup

AIR-2179-ff (Fix 'Try Again' feature and minor cleanup)

---

src/app/image-group-page/image-group-page.component.ts
src/app/shared/image-group.service.ts

LoadingState: Use lower case ppt and zip across the board because it is used in styles for icons

2179-Final

---

src/app/category-page/category-page.component.pug

Category Page: update  value to use new full url instead of old viewer2 url

AIR-2309(remove prepending of viewer2)

---

src/app/modals/edit-personal-collection/edit-personal-collection.component.scss

- EditPC-Comp: change image preview height to auto instead of 100

Edit Personal Collection image preview fix

---

src/app/modals/add-to-group/add-to-group.component.pug
src/app/modals/add-to-group/add-to-group.component.ts

Add to groups updates!
* Make sure the recent groups are loading.
* Make sure searching group by numbers returns correct results.
* Make sure we are showing the loading icon while the user is searching for a group

AIR-2318 & AIR-2305

---

src/app/search-page/search-page.component.ts
src/app/shared/script.service.ts
src/app/shared/script.store.ts

ScriptStore: Adds mouseflow script
Search page: bind _mfq to window for mouseflow
Mouseflow call from localhost on search page:

AIR-2338(Add mouseflow)

---

src/assets/i18n/en.json

Added promo for detail views to homepage

New homepage ad

---

src/app/asset-page/asset-page.component.ts
src/app/modals/add-to-group/add-to-group.component.ts
src/app/shared/datatypes/asset.interface.ts

+ IIIF quality/format handling

Air 2328: Capping size of image downloads to prevent stalling

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts

- Handle present mode exit for all fullscreen events
- Ensure "curtain" never shows outside of fullscreen

AIR-2361: Blank screen when exiting present mode immediately

---

src/app/search-page/search-page.component.ts

It looks like page views have to be manually reported in an SPA

Air 2338: Mouseflow follow up 

---

package.json
server/server.ts
src/app/asset-page/asset-page.component.ts
src/index.html
yarn.lock

+ Disable js for bots on server-rendered pages
+ Return 503s if asset is not rendered
+ Attach canonical header if asset is rendered

Air 2334: Resolve Googlebot loading errors

---

src/app/_services/auth.service.ts
src/app/login-form/login-form.component.ts
src/app/pact/user-access.pact.spec.ts
src/app/pact/user-register.pact.spec.ts
src/karma.conf.js

Pacts for:
- Login
- /userinfo

Air 2282: User access Pacts

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.ts

- We auto zoom when the viewer is first loaded, track the zoom event after the auto zoom is finished
- Make sure the event is logged once per user per asset per session

AIR-2396 (Captain's log event: Zoom on image)

---

src/app/home/featured/featured.component.pug
src/assets/i18n/en.json

FeaturedComp Template: Handle, and clean for sahara specific featured component link values

2385 : Sahara Fixes

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts

- Display different error message according to search 3 error response

AIR-2425 (Artstor search: Use notices and error from search 3 response.)

---

src/app/_services/script.store.ts
src/app/search-page/search-page.component.ts

- Remove Ethnio survey from search page

AIR-2451 (Remove Ethnio Survey)

---

src/app/_services/flag.service.ts
src/app/_services/image-group.service.ts
src/app/image-group-page/image-group-page.component.ts

Flags, Image Group Service, Image Group Page: Clean out newExport flag

AIR-2442(clean out newExport flag)

---

src/app/_services/asset-search.service.ts

- Increase the limit to 30 because our intended filter appear at index 25 and 29

AIR-2364 (Increase the limit for classification filter in advanced search)

---

src/assets/i18n/en.json

We want to try changing my collections to personal collections for the hack

Updating browse menu option

---

src/app/_services/assets.service.ts
src/app/asset-filters/asset-filters.component.ts
src/app/asset-filters/asset-filters.service.ts
src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts
src/app/asset-page/asset-page.component.ts
src/app/shared/assets.spec.ts
src/app/shared/search/search.component.ts

Change the default values from 24 to 48

AIR-2353 (Default to 48 results per page)

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/shared/datatypes/asset.interface.ts

- Hyperlink subject field
- Track GA event
- Merge stage to get the recent change of formatMetadata

AIR-2459 (Hyperlink Subject field) & AIR-2469 (GA event: Track subject link clicks)

---

src/index.html

Added the block of code provided by AppD to implement End User Monitoring (EUM) on AIW.
https://www.appdynamics.com/product/end-user-monitoring/

AIR-2495: Add AppD EUM monitoring to AIW

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/nav-menu/nav-menu.component.ts

This PR resolves three, small lingering issues.
- AssetPage: remove call to deleted method closeAddToGroupTooltip
- NavMenu: uncomment closeNavMenuDropdowns
- AssetPage: handle loaded metadata for asset.id

brett-fixes-branch

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.html
src/app/asset-page/artstor-viewer/artstor-viewer.component.scss
src/app/asset-page/artstor-viewer/artstor-viewer.component.ts

Viewer - pdf viewer style improvements

AIR-2374-design

---

src/app/asset-page/licenses.ts

Resolves [PLATO-149](https://jira.jstor.org/browse/PLATO-149)
Adds the "Creative Commons: Free Reuse (CC0)" license

PLATO-149: Add CC0 license

---

src/assets/i18n/en.json

Updated both featured and public ones. They should be the same.

Updated featured homepage slideshow

---

src/app/account-page/account-page.component.pug
src/app/register/register.component.pug

Praveena noticed the same issue occurring on the Register page, so the fix was applied to that template also

PALS-100: Settings Page "Role at Institution" Field Lacking Label

---

package.json
src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts

Release AIW 2.7.16
Resolves [PLATO-245](https://jira.jstor.org/browse/PLATO-245)

Release AIW 2.7.16

---

config/webpack.test.js
src/app/white-label-config.ts
src/environments/environment.spec.ts

Disabled Zendesk until we can figure out bug fix. Also, fixed webpack test config to support multiple loaders for pug files

PLATO-253: Disable Zendesk until we can fix issue and fixed webpack test config

---

src/app/register/register.component.pug

Links are now accessible via keyboard ⌨️ ✨

PALS-102: Register Page "Login" and "Help" Links Not Accessible via Keyboard

---

src/app/account-page/account-page.component.pug
src/app/account-page/account-page.component.ts
src/app/modals/change-password/change-password.component.pug

"Change Password" link on Settings page is now accessible via keyboard ⌨️ ✨

PALS-103: Settings Page "Change Password" Link Not Accessible Via Keyboard

---

src/app/_services/script.store.ts
src/app/asset-page/asset-page.component.ts
src/app/image-group-page/image-group-page.component.ts

[PLATO-334](https://jira.jstor.org/browse/PLATO-334)
Remove ethnio survey from the asset and image group pages

PLATO-334: Remove ethnio survey

---

src/app/_services/log.service.ts
src/app/asset-page/asset-page.component.ts

- AssetPage: Adds new method `trackItemView` with logic for determining access values.
- Adds `reason_for_authentication` `has_access` and `entitlement_map` to additional fields.
*NOTE* - There is some cleanup unrelated to issue 165, removing needless commented out code.

PALS-165( new artstor_item_view C5 fields)

---

src/index.html

PALS-144: Zooming and scaling must not be disabled

---

src/assets/i18n/en.json

Resolves[PALS-141](https://jira.jstor.org/browse/PALS-141).
When accounts aren't set up properly for SAML, we want to give users a more informative message.

PALS-141: Update SAML error message

---

src/app/asset-page/asset-page.component.ts
src/app/image-group-page/image-group-page.component.ts

- Fix error handling for exporting group
- Log asset id when access is not granted

PLATO-363: Fixes to c5 logs

---

src/app/_services/metadata.service.ts
src/app/asset-page/asset-page.component.ts
src/app/shared/datatypes/asset.interface.ts

Start logging the doi for the following event types
`artstor_view_item`
`artstor_download_single_image`
`artstor_image_view_download`

PLATO-391: Log doi for item specific events

---

src/app/_services/script.store.ts
src/app/asset-page/asset-page.component.ts
src/app/image-group-page/image-group-page.component.ts
src/app/search-page/search-page.component.ts

Removed the ethnio survey from asset, image groups, and search pages.

PLATO-384: removed ethnio survey

---

src/app/register/register.component.ts

Resolves [PALS-181](https://jira.jstor.org/browse/PALS-181)
Send user to link route if samlToken is present

PALS-181: When Shibboleth IdP does not send email address, users cannot link an existing account

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/browse-page/browse-groups/general-search.component.pug
src/app/browse-page/browse-groups/groups.component.pug

Add `h1` tags to item view and image group pages for accessibility. Part of VPAT Conformance.

PLATO-217-220: Add first-level headings to item view and image group pages

---

src/app/asset-grid/asset-grid.component.pug
src/app/browse-page/browse-groups/groups.component.pug
src/app/browse-page/commons.component.pug
src/app/browse-page/institution.component.pug
src/app/browse-page/institution.component.ts
src/app/browse-page/library.component.pug
src/app/browse-page/my-collections.component.pug
src/app/home/home.component.pug
src/sass/core/_typography.scss
src/sass/core/_variables.scss
src/sass/modules/_filters.scss

This PR addresses the accessibility issues reported in SRCHX-237.

SRCHX-237: Reported pages should have heading level 1.

---

src/app/app.component.ts
src/app/login/login.component.ts
src/app/register/register.component.ts

Resolves [PALS-170](https://jira.jstor.org/browse/PALS-170)
Title is now being set on Home, Register and Log in pages

PALS-170: Document title element missing/empty

---

src/app/_services/toolbox.service.ts
src/app/asset-page/artstor-viewer/artstor-viewer.component.html
src/app/asset-page/asset-page.component.ts

[PLATO-227](https://jira.jstor.org/browse/PLATO-227)
More tweaks to the tab ordering. This time Michael, Nick and Sean have already looked at the changes locally and given the 👍.

PLATO-227: Fixing tab ordering so we can announce what is on the screen

---

src/app/modals/search-modal/search-modal.component.pug

WCAG: Links need to look like links

SRCHX-241: Make Help button appear as underlined

---

src/app/register/register.component.pug
src/app/register/register.component.ts

Apply focus to error messages on Register page after a timeout so VoiceOver doesn't announce them too soon.

PALS-115: Register Page: Error Messages Aren't Announced via Screen Reader

---

src/app/_local-pc-asset.service.ts
src/app/_services/account.service.ts
src/app/_services/image-group.service.ts
src/app/modals/loading-state/loading-state.component.ts

https://jira.jstor.org/browse/PALS-244

PALS-244: Resolve circular dependency warnings in Artstor

---

.github/PULL_REQUEST_TEMPLATE.md

Resolves PALS-96
Created PR template for Artstor Repo

PALS-96 Create PR template for Artstor Repo

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts
src/app/asset-grid/thumbnail/thumbnail.component.pug
src/app/modals/add-to-group/add-to-group.component.pug
src/app/shared/pagination/pagination.component.pug

Resolves [PLATO-496](https://jira.jstor.org/browse/PLATO-496)
Fixes automated accessibility errors generated from the QA gem.

PLATO-496: Automated accessibility fixes for image group page

---

src/app/shared/pagination/pagination.component.ts

Resolves PLATO-496
Forgot to re-add a variable when testing out a different solution

PLATO-496: Adding missing pagination variable

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts

PLATO-540
Log artstor_print_image in C5. Also, add referring_requestID to artstor_print_image log

PLATO-540: Log artstor_print_image in C5

---

src/app/_services/script.store.ts
src/app/app.component.ts
src/index.html

Resolves PALS-276
Add brand survey on Artstor using ethn.io

PALS-276: Add Brand survey on Artstor

---

src/app/_services/script.service.ts
src/app/_services/script.store.ts
src/app/app.component.ts

Resolves PALS-296
Removed survey script and added error handling

PALS-296: Removed survey

---

src/app/account-page/account-page.component.pug
src/app/register/register.component.pug
src/app/shared/footer/footer.component.scss
src/sass/app.scss
src/sass/core/_typography.scss

Resolves PALS-97
Resolves PALS-99
Resolves PALS-105
Fixed smallest font size to 12px on footer and home page.
Removed aria labels on register page.
Enabled autocomplete on settings form.

PALS-97-99-105: Accessibility fixes

---

src/app/search-page/search-page.component.ts

Resolves SRCHX-738
Changes in this PR ensure that we log each search event inside captains log just once.

SRCHX-738: Fix multiple search logs for a single search event

---

src/assets/i18n/en.json

Resolves PALS-731
We updated AIW Slideshow as per latest requirements.

Update slideshow content

---

src/app/_services/script.store.ts
src/app/asset-page/asset-page.component.ts
src/app/image-group-page/image-group-page.component.ts
src/app/search-page/search-page.component.ts

Removes ethino survey that was introduced in: https://github.com/ithaka/aiw-ui/pull/1307

PLATO-1281: Remove ethino survey

---

src/assets/i18n/en.json

Add j to correct typo

---

src/app/_services/script.store.ts
src/app/app.component.ts

PLATO-1444
Add survey to entire artstor site

PLATO-1444: Add sitewide survey

---

src/assets/i18n/en.json

PALS-870: Update slideshow for March

---

src/app/_services/flag.service.ts
src/app/app.component.ts
src/app/app.service.ts
src/app/shared/footer/footer.component.ts
src/index.html

Resolves SRCHX-1166
Changes in this PR ensure that the google translate and zendesk features are compliant with the OneTrust cookie preferences set by the user. The changes are implemented behind `enableOneTrust` feature flag. 

SRCHX-1166: OneTrust Cookie Compliance

---

package.json
src/index.html

Release v2.7.162

---

src/app/search-page/search-page.component.pug
src/app/search-page/search-page.component.ts
src/sass/core/_layout.scss

Resolves SRCHX-1203
add link on aiw search results to jstor basic search

SRCHX-1203: link to jstor basic search

---

src/app/_services/script.store.ts
src/app/image-group-page/image-group-page.component.ts

PLATO-1708
Adds survey to image group page

PLATO-1708: Survey on image group page

---

.gitignore

Ignore `.tool-versions`, a config file used by asdf.

Ignore asdf config file

---

src/assets/i18n/en.json

Updating homepage slideshow for June

---

src/assets/i18n/en.json

replacing floyd image on homepage

---

src/app/_services/script.store.ts
src/app/asset-grid/asset-grid.component.ts
src/app/modals/search-modal/search-modal.component.ts
src/app/search-page/search-page.component.ts

SRCHX-1280: Add survey to advanced search

---

src/assets/i18n/en.json

Homepage slideshow content for Aug/Sept

---

src/app/modals/role/role.component.ts

Resolves PALS-1151
emit google analytics events for role prompt

PALS-1151: emit google analytics events for role prompt

---

src/app/modals/role/role.component.ts

Resolves PALS-1175
update the correct attr on the user so that the profile automatically updates

PALS-1175: update the correct attr on the user so that the profile automatically updates

---

src/app/_services/script.store.ts
src/app/app.component.ts
src/app/asset-page/asset-page.component.ts
src/app/home/home.component.ts
src/app/image-group-page/image-group-page.component.ts
src/app/search-page/search-page.component.ts

Resolves PALS-1210
We want to add the new Ethnio survey to homepage, item detail,  search results and image group.

PALS-1210: Add Ethnio survey to homepage, item detail,  search results and image group

---

src/app/app.component.ts

Resolves PALS-1210
We want to add the new Ethnio survey to homepage, item detail, search results and image group. Want to remove the survey from remove survey from src/app/app.component.ts.

PALS-1210: Remove survey from src/app/app.component.ts

---

src/assets/i18n/en.json

Resolves PALS-1247
updating to link to the group instead of the specific asset.

Link correction

---

src/app/_services/auth.service.ts
src/app/app.component.ts
src/app/modals/aji-intercept/aji.component.ts

Resolves PALS-1481
- Make the remind me later and X button on the modal prevent future prompting (for now)
- Show the prompt when the auth data for the page is reinitialized. Not on refresh.

PALS-1481: clean up some open issues

---

src/app/_services/auth.service.ts
src/app/app.component.ts
src/app/modals/aji-intercept/aji.component.pug
src/app/modals/aji-intercept/aji.component.scss
src/app/modals/aji-intercept/aji.component.ts

PALS-1482: Build Post Login AJI banner on AIW

PALS-1482: Build Post Login AJI banner on AIW - Contd.

---

src/app/_services/auth.service.ts
src/app/app.component.ts
src/app/modals/aji-intercept/aji.component.pug
src/app/modals/aji-intercept/aji.component.scss
src/app/modals/aji-intercept/aji.component.ts

Revert "PALS-1482: Build Post Login AJI banner on AIW - Contd."

---

src/app/_services/script.store.ts
src/app/asset-page/asset-page.component.ts
src/app/image-group-page/image-group-page.component.ts
src/app/search-page/search-page.component.ts

Resolves PLATO-2543
Update ethnio survey to show on image groups, search results, asset page

PLATO-2543: Update ethnio survey

---

src/app/_services/auth.service.ts
src/app/modals/aji-intercept/aji.component.ts

Resolves PALS-1534
- continues from https://github.com/ithaka/aiw-ui/pull/1403

PALS-1534: take on from https://github.com/ithaka/aiw-ui/pull/1403

---

src/app/_services/account.service.ts
src/app/_services/auth.service.ts
src/app/modals/aji-intercept/aji.component.ts

Pals 1534: Continues from https://github.com/ithaka/aiw-ui/pull/1404

---

src/app/_services/account.service.ts
src/app/_services/auth.service.ts
src/app/app.component.ts
src/app/modals/aji-intercept/aji.component.pug
src/app/modals/aji-intercept/aji.component.ts
src/app/post-login-banner/drop-banner/drop-banner.component.pug
src/app/post-login-banner/drop-banner/drop-banner.component.ts
src/app/post-login-banner/static-banner/static-banner.component.pug
src/app/post-login-banner/static-banner/static-banner.component.scss
src/app/post-login-banner/static-banner/static-banner.component.ts

PALS-1534
- updates to preferences value showAjiModalOrBanner
- changes to post login banner expand/close button

PALS-1534: Continues from https://github.com/ithaka/aiw-ui/pull/1405

---

src/app/_services/auth.service.ts
src/app/app.component.ts
src/app/modals/aji-intercept/aji.component.ts
src/app/post-login-banner/drop-banner/drop-banner.component.ts

PALS-1545
`event` is tracked as `event action` in GA.

PALS-1545: AIW On-platform Message - Create Event Tracking

---

src/app/_services/auth.service.ts
src/app/app.component.ts
src/app/modals/aji-intercept/aji.component.pug
src/app/modals/aji-intercept/aji.component.ts
src/app/post-login-banner/drop-banner/drop-banner.component.pug

PALS-1545: Event tracking for on platform messaging. Extends https://github.com/ithaka/aiw-ui/pull/1407

---

src/app/app.component.ts
src/app/modals/aji-intercept/aji.component.ts

PALS-1545: Event tracking for on platform messaging. Extends https://github.com/ithaka/aiw-ui/pull/1408

---

src/app/_services/script.store.ts
src/app/app.component.ts
src/app/asset-page/asset-page.component.ts
src/app/image-group-page/image-group-page.component.ts
src/app/search-page/search-page.component.ts

PALS-1629: clean up old survey, and add new ethnio survey to all pages

PALS-1629: clean up old survey, and add new ethnio survey to all pages

---

package.json
src/app/_services/auth.service.ts
src/app/login-form/login-form.component.ts
src/app/login/login.component.ts
src/app/modals/pwd-reset/pwd-reset.component.pug
src/app/modals/pwd-reset/pwd-reset.component.ts
src/assets/i18n/en.json

Refactoring the password reset modal, to check whether the user has submitted repeated requests, and block accordingly.

PALS-1713: Update password reset endpoint, and check for excess submission attempts. 

---

src/app/_services/auth.service.ts
src/app/login-form/login-form.component.ts
src/app/login/login.component.ts
src/app/modals/pwd-reset/pwd-reset.component.pug
src/app/modals/pwd-reset/pwd-reset.component.ts
src/assets/i18n/en.json

Linting the associated files ahead of PALS-1713

PALS-1713-refactor: lint

---

src/app/modals/pwd-reset/pwd-reset.component.pug
src/app/modals/pwd-reset/pwd-reset.component.ts
src/assets/i18n/en.json

PALS-1774: put up temporary error messaging as we work on updating the pwd reset flow

PALS-1774: temporary error messaging for artstor

---

package.json

v2.10.66 - bumping the version

v2.10.66 - bumping the version

---

src/app/app.component.ts
src/app/shared/footer/footer.component.pug
src/assets/styleguide/styles/all.css
src/sass/app.scss

Resolves PALS-2038
PALS-2038: removing google translate

PALS-2038: removing google translate
