ithaka/aiw-ui

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/login/login.component.ts
src/app/shared/auth.service.ts
src/app/shared/nav/nav.component.ts

Steps to recreate problem:
1. Be Ip auth'd
2. Search "ornamental initials" on Jstor
3. Explore result image in Artstor
4. While in Artstor, delete all library.artstor.org cookies
5. Close Artstor tab
6. Leave VPN, lose ip auth
7. Explore result image in Artstor again, no modal will show

Air 1696: Ensure asset loads after user access has loaded this session

---

src/app/browse-page/browse-groups/groups.component.pug
src/app/browse-page/browse-groups/groups.component.ts
src/app/browse-page/browse-groups/tag-filters.service.ts
src/app/browse-page/browse-groups/tags-list.component.pug
src/app/browse-page/browse-page.component.scss
src/sass/modules/_filters.scss

- Selected tags are pushed to the top once selected
- Add selected tags above the image groups,  and once more than one tag is selected, there is clear all button showing up
- Only show 15 tags by default and user has a chance to expend it
- Change the style of the tags according to the design

Air-1412: Group tags: Display and select tags

---

config/webpack.prod.js

"response-cache-control" query param is attached to the bundled JS files to tell S3 to return a cache control header which will then be picked up by Fastly

Webpack: Attach cache query param to js files

---

src/app/image-group-page/ig-download-modal/ig-download-modal.component.pug
src/app/image-group-page/ig-download-modal/ig-download-modal.component.ts
src/assets/i18n/en.json

- Show error message when failure according to image group size
- Move the long sentences to en.json
P.S. If logged in as air01, can use "ppt download" private image group to test, which is a big image group.

AIR-1707 (PPT/zip download error message)

---

config/webpack.prod.js

Avoid apps-gateway issue when passing the cache control query param

AIR-1567: Webpack: Place js bundles in "/assets"

---

src/app/browse-page/browse-groups/groups.component.ts

Binder made an api update to change the functionality of the search api. level=created is now the way to get the user's groups. These changes alter how we call the endpoint, which will provide for accessing a user's private groups with `level=private` in the future

Get users groups with level=created

---

src/app/shared/asset-search.service.ts

Refactors, wraps some of the logic asset-search.service in order to isolate some of the search method logic.
-defines a filterOptions object in the search method.
-defines applyFilters function that wraps a large chunk of logic currently in search
-defines initQuery that wraps logic currently in search
-In AssetSearchService.search, we defined `let startIndex = ((options.page - 1) * options.size) + 1;`
and that value is never used - so it has been removed.

Refactor AssetSearchService.search

---

src/app/asset-page/asset-page.component.ts

In setCollectionLink, we are now checking the collectionId, but some of the collections have collectionId of NaN. In this case, check the id in the collections array instead.

AIR-1729 （ADL collection links on asset pages broken）

---

package.json
yarn.lock

- Viewer update makes it so the thumbnail is always loaded on the page, and other viewers stack on top
- Adds a background to other viewers to cover the thumbnail
- Having the thumbnail always available makes it accessible to the Googlebot

AIR-1702: [yarn install] Viewer @1.1.6, web crawler support

---

src/app/browse-page/card-view/card-view.component.pug
src/app/browse-page/card-view/card-view.component.ts

- When there is no group owner name, show '-' as creator and make it not linkable
- On level=created, don't rely on if the owner_id=profileId to check group type. Since on level=created, everything returned by the group call will be my group, I only need to check group_type of 100 or 200. I I add this logic to the code so that the group type will be correct even if I don't have owner id.
- Did some clear up, and made creator clickable on mobile.

AIR-1772 (Handle cases when owner name and owner id for image groups doesn't exist)

---

src/app/browse-page/browse-groups/groups.component.ts

For group search, we need to url encode the term param, as well as replace forward slashes with backslashes

Implement groups.component.cleanGroupSearchTerm

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts
src/app/asset-page/asset-page.component.ts
src/app/shared/assets.service.ts

To recreate:
- Upload PC assets
- Add PC assets to your own group
- Delete one of the PC assets
- Open group, and see restricted images message
- You can now "Remove" deleted assets, and clear the alert

Air 1761: Allow group owner to remove deleted assets

---

config/pact.publish.js
src/app/pact/metadata-api.pact.spec.ts
src/app/shared/datatypes/asset.interface.ts

Adds 'image_compound_urls' to /metadata, and makes some changes to ensure we're type checking properties in nested array items

Air 1717: Add compound property to /metadata Pact

---

src/app/modals/generate-citation/generate-citation.component.ts

The previous changes to to citation.component would output citation urls like:
library.artstor.org//asset/MMA_IAP_1039652085
This fixes the double `//`

Fix citation slash mistake

---

src/app/shared/metadata.service.ts

It was already set to false, so should be a completely innocuous change

/metadata: Remove remaining "legacy" param

---

src/app/asset-grid/asset-grid.component.ts
src/app/browse-page/card-view/card-view.component.ts

It was a pretty specific bug that would happen only if "deleted assets" wasn't reset, and the assets didn't exist in the group

Air 1829: Safely check index before splicing

---

src/app/image-group-page/image-group-page.component.pug
src/app/image-group-page/image-group-page.component.ts
src/app/pcollection-page/pcollection-page.component.pug
src/app/pcollection-page/pcollection-page.component.ts

Add unaffiliated modal for pcollection and image-group-page pages
- We need to check for public users clicking or pasting a link straight to group/id or pcollection/id
pages.

Add unaffiliated modal for pcollection and image-group-page pages

---

src/sass/modules/_buttons.scss

- For Chrome and Safari, create an outline around the main nav when focused, which looks like the browser's default focus style.
- For FireFox, the default outline looks terrible. Specify FireFox's focus style with "-moz-focusring"

AIR-1743 (Indicate focus in main nav by more than color)

---

src/app/asset-grid/thumbnail/thumbnail.component.pug
src/app/asset-grid/thumbnail/thumbnail.component.ts

- Add GA event for clicking on the little people icon.
- Event action: "view associated images"
- Label: thumbnail's objectId or artstorid depending on the thumbnail 
- Distinguish between associated icon click and cluster icon click
Note: Job of AIR-1877 also done in this branch because it is one piece of code!!!

Air-1876 (GA event: click on associated images icon)

---

src/app/modals/search-modal/search-modal.component.pug
src/app/modals/search-modal/search-modal.component.ts
src/sass/modules/_buttons.scss

- Make the dropdown buttons in the "in any field" and "and/or" accessible.
- Make the CE/BCE options accessible.
- Make the help link accessible.
- Disable tabbing outside of the modal.
- Change secondary button styles in _buttons.scss to get rid of the grey look when buttons are focused.
- Check for Tab key inside dateKeyPress function to enable tabbing on FireFox. (Otherwise, the keypress event will prevent user from tabbing to other elements on FireFox. )

Air-1845 (Make advanced search modal keyboard accessible)

---

src/app/modals/generate-citation/generate-citation.component.pug
src/app/modals/generate-citation/generate-citation.component.scss
src/app/modals/generate-citation/generate-citation.component.ts
src/sass/modules/_buttons.scss

- Focus on the title of the modal
- Disable tabbing outside the modal
- Enable tabbing of the button of Copy-to-Clipboard
- Change the focus style of help link
Note: Since we use "focusout" event on the last button, when we hit "shift tab" while focusing on the last button, we will go to the title instead of the previous button. This behavior appears on every newly changed modal. Currently haven't figured out a way to solve it.

AIR-1848 (Make generate citation modal keyboard accessible)

---

src/app/asset-page/asset-page.component.ts

- In function genDownloadViewLink() we make the download button disappear and in function runDownloadView() we make it back. However, we wrap the function runDownloadView() in an if clause. So if we don't enter the if clause we will never make the button back. Add  an else to solve it.

AIR-1873 ('Download' button disappears on asset page after downloading media file)

---

src/app/login/login.component.ts

Simple reference issue when stashedRoute does not yet exist or is already cleared

Institution login: stashedRoute fix

---

src/app/asset-filters/asset-filters.component.ts

**Test Note**: The problem in the ticket doesn’t occur on local because we are calling `//stage.artstor.org/api/search/v1.0/search`  on local and stage. The pipes only occur when we call `//library.artstor.org/api/search/v1.0/search`. So to test, we can set line 158 of auth.service.ts to be `this.solrUrl = '//library.artstor.org/api/search/v1.0/search'` to make the problem occur on local and see the difference of the change.

AIR-1924 (Fix artClassification filter on production)

---

src/app/app.routes.ts
src/app/legacy.service.ts
src/index.html

Links like:
http://sscommons.org/openlibrary/secure/ViewImages?id=4jEkdDElKzQ3RkY6fz57RH1DOHQqeFlxdg%3D%3D&userId=gDFB&zoomparams=
Will be redirected to:
http://library.artstor.org/openlibrary/secure/ViewImages?id=4jEkdDElKzQ3RkY6fz57RH1DOHQqeFlxdg%3D%3D&userId=gDFB&zoomparams=
So we can verify our app will handle them by replacing "sscommons.org" with our hostname
(To test locally you will also need to add the hash "/#" to the path)

Air 1544: sscommons.org redirects

---

src/app/asset-page/asset-page.component.pug
src/assets/i18n/en.json

- About the problem: The images are actually deleted but it needs some time for it to be really deleted. In the meantime, the deleted thumbnail still appears in the personal collection and it is still clickable, which leads the user to land on an asset page that has content unavailable. 
- About the solution: We now update the message after a successful deletion from personal collections to inform users that there may be a delay.

Air-1625 (Error after deleting 3 or 4 personal collection files in ADL)

---

src/app/legacy.service.ts

Fixing ids when handling links such as:
/openlibrary/#3%7Ccollections%7C7730115%7C%7CBucknell20University3A20Artists2720Books20Collection%7C%7C%7C

Open Library links: Prepend "8" to collection id

---

src/app/app.component.ts
src/app/login-form/login-form.component.pug
src/app/login/login.component.pug
src/app/modals/change-password/change-password.component.pug
src/assets/i18n/en.json

- Some fields read the whole page problem should be solved in a general way in the app component
- Change e-mail field placeholder
- Change institution dropdown placeholder
- Correct tabindex
Note: ng2-completer is still having weird behavior of reading half of the previous thing. AIR-1999 is created for this.

Air-1970 (Add and create labels on Log In page)

---

src/app/asset-page/asset-page.component.ts

- Media files cannot be downloaded from localhost, the href we are using: "//stage.artstor.org/media/SS34216_34216_33832185/22" is reporting "This site can’t be reached" (So I cannot test from localhost). 
-Media files can be downloaded from prod. Before added to image group, the download link of a media file is something like "/media/SS34216_34216_33832187/21". After added to image group, we will add image group id to the url, resulting the href to be "/media/SS34216_34216_33832187/21&groupid=f374dae5-0a13-49ef-9883-f6ba16b20cfb". 
- It turns out that **the file can only be downloaded without the groupid parameter being added**.
- Manually check for media file and don't append groupid to solve this (I realize it is really ugly code. I don't know if it is a good solution. It should work …

AIR-1962 (Unable to download media files from image groups)

---

src/app/category-page/category-page.component.ts

- `/api/category` is no longer available, but `api/v1/categorydesc` returns the category name we need

AIR-2027 (ADL collection titles not displaying on collection page)

---

src/app/asset-grid/thumbnail/thumbnail.component.pug

Thumbnail comp template: For downgraded MV media icon, add media.format is null to condition to fix MV icon layout

2164-fix Badge / Icon layout in downgraded media icon conditional

---

src/app/shared/assets.service.ts

We had a loophole where a search subscription could overwrite subsequent searches, and this fix properly prevents that from happening

AIR-2198: Asset search: hasOwnProperty can't be used for proto properties

---

src/app/app.module.ts
src/app/image-group-page/image-group-page.component.pug
src/app/image-group-page/image-group-page.component.ts
src/app/image-group-page/index.ts
src/app/image-group-page/terms-and-conditions/terms-and-conditions.component.pug
src/app/image-group-page/terms-and-conditions/terms-and-conditions.component.ts
src/app/nav-menu/nav-menu.component.pug
src/app/shared/group-title/group-title.component.pug
src/app/shared/group-title/group-title.component.ts
src/app/shared/image-group.service.ts
src/assets/i18n/en.json

- Create new component Terms and Conditions.
- For igDownloadTrigger EventEmitter, specify export type by emitting a string "PPT", "ZIP" or "GoogleSlides". If no string specified, use old download image modal.
- Give export type as input to the Terms and Conditions modal so it knows which download to trigger when user agrees with the terms.
- Assign session storage called "termAgreed" with a boolean value to make the modal display only once per session.
- Currently clicking on "I agree" on Terms and Condition modal will have same effect as clicking on "Request PPT"/"Request Zip" on the old download image modal.
- Add label for "I agree" button according to Kelsey's suggestion.
Note: The download process will not be triggered by clicking on "I agree" on Terms and Conditions modal or on the …

AIR-2134 (Display "Exporting Terms and Conditions" modal once per session)

---

src/app/shared/toast/toast.component.scss

- Set a max-width to prevent text div being push to next line
- Make toast smaller when the window is small (According to Kelsey, the width is 280px)
- Wrap long word

AIR-2217 (Design Refine: toast fix, text box being pushed below icon)

---

src/app/modals/add-to-group/add-to-group.component.ts
src/app/modals/new-ig-modal/new-ig-modal.component.ts

Note: It doesn't interfere the original "addToGroup" event. When I add a detail view to group I should expect two events: "addDetail" AND "addToGroup".

AIR-2095 (GA Events for Adding Details to Groups)

---

src/app/modals/session-expire/session-expire.component.pug
src/sass/modules/_modals.scss

Praveena and I believe the users situation is caused by not giving priority to the Session Expired modal, which allowed the user to try to continue to download or add items while their session was expired

AIR-2191 Modals: Show session expired modal first, add priority classes

---

src/app/login-form/login-form.component.pug
src/app/login-form/login-form.component.ts
src/app/login/login.component.pug
src/app/login/login.component.ts
src/app/modals/pwd-reset/pwd-reset.component.pug
src/app/modals/pwd-reset/pwd-reset.component.ts

- Emit the email address from login-form component 
- Receive the email address at login component
- Login component then feed it to pwd-reset component
Note: I use the event emitter because we want the pwd-reset component to receive the email address even if user didn't submit any form

AIR-2247 (Add email input from pw reset modal)

---

src/app/login-form/login-form.component.ts
src/app/modals/pwd-reset/pwd-reset.component.pug
src/app/modals/pwd-reset/pwd-reset.component.ts
yarn.lock

Fixes:
1. For the Ghost modal and the Password reset modal, a user's not able to tab to the "x" or close button
2. The validation looks like it's on a timer? Can we turn off the timer?
4. I'm able to tab to elements outside the *success* modal after password reset, can we turn that off?

Air 2240: Follow up fixes

---

src/app/modals/new-ig-modal/new-ig-modal.component.ts

- The labels are not showing in Analytics because of a wrong setting on the TagManager website. So setting a correct variable on TagManager does the fix once for all.
- This branch just fixes the label for copyGroup where it is undefined.

AIR-2248 (Analytics/GTM: Events with missing information [PLACEHOLDER])

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.ts

- Add a captain's log event for when a user enters fullscreen mode (now it's only on the asset page, using the arrows button).
- Event: artstor_enter_fullscreen

AIR-2267 (Captain's log event: enter fullscreen mode)

---

package.json
src/app/app.component.ts
src/app/app.module.ts
src/app/environment.ts
yarn.lock

After a lot of trial and error, I discovered the Sentry import does not compile correctly from the environment.ts providers convenience file. Couple other notes:
- Sentry no longer prevents the errors from logging correctly so using it locally doesn't hurt anything now
- Our environment variables do work, that was an assumption I made

AIR-2191 Sentry: Move import to app.module

---

src/app/_services/metadata.service.ts
src/app/shared/datatypes/asset.interface.ts

- Send groupid as query parameter to /api/imagefpx and /media calls when coming from a group

AIR-2296 (Need groupid to play audio/video files and download media files)

---

server/server.ts
src/index.html

Links such as:
library.artstor.org/library/#3%7Ccollections%7C87730435%7C%7CBrooklyn20College20Listening20Project%7C%7C%7C
Should be redirected to the appropriate collection page.

AIR-2292: Handle legacy link redirects

---

src/app/asset-grid/asset-grid.component.ts

- Change from indexOf to findIndex because this.if.items is an array of objects instead of an array of numbers

AIR-2391 (Remove deleted image button not functioning)

---

src/app/_services/asset-search.service.ts
src/app/_services/assets.service.ts

- Change `content_types` to `content_set_flags` in the query
- Change `filter_query` to `filter_queries` in the query
Note: the two variables "contentQueryKey" & "filterQueryKey" are temporarily set up to simplify the code because currently we need to account for two types of search, they can be removed after we completely switched to search3.

AIR-2398 (Support Search3 filters with flag)

---

src/app/_services/thumbnail.service.ts

- There is a missing `clusterid` in `AssetThumbnail`, after adding it back it works fine

AIR-2403 (Disabled Cluster Icon)

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.scss

AssestViewer SCSS: remove tooltip-inner style so the definition in app.scss isn't overridden

Viewer Tooltip Fix - PDF Fast Follow

---

src/app/_services/group.service.ts
src/app/asset-page/asset-page.component.ts
src/app/register/register.component.ts

For TypeError `Cannot read property 'id' of undefined` that fired 37 times: 
- On asset page, the `this.assets[0]` will take some time to load, otherwise it is undefined
For TypeError `Cannot read property 'isLoggedIn' of null`:
- In group service, check the `cachedUser` before read `isLoggedIn`

AIR-2350 (Clean up Sentry deluge)

---

src/app/home/featured/featured.component.pug
src/assets/i18n/en.json

- "Featured collections" change to "What's new"
- The link text "View all collections" change to "Read more on the blog"
- The link is updated to: https://www.artstor.org/blog/

AIR-2385 (Update copy for library.artstor.org slideshow)

---

src/app/_services/group.service.ts
src/app/browse-page/browse-groups/groups.component.pug
src/app/modals/add-to-group/add-to-group.component.pug
src/app/modals/add-to-group/add-to-group.component.ts

It looks like the primary fix to this issue was made by Jialin 2 days ago, when cleaning up a reference to "cachedUser.isLoggedIn", however I fixed a couple other things that, depending on the path the user took, may have caused an issue:
- When a group is created or destroy, reassess whether the user has private groups
- Properly display an error message when Recent Groups do not load in the Add to Group modal
- When we query for a user's groups, set "hasPrivateGroups" to false if no groups return
- Fix the error display in the Groups Browse layout

Air 2412: User cannot add to image group they created

---

src/app/register/register.component.ts

- `this.shibParameters` is an object, so check the email instead of checking itself

AIR-2389 (On Registration, "Log in" link takes users to the "link account" page)

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.html
src/app/asset-page/artstor-viewer/artstor-viewer.component.scss
src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.scss
src/assets/img/icon-compare.svg
src/assets/img/icon-exit-fullscreen.svg
src/assets/img/icon-fit-to-view.svg
src/assets/img/icon-present.svg
src/assets/img/icon-remove-from-comparison.svg
src/assets/img/icon-zoom-in.svg
src/assets/img/icon-zoom-out.svg
src/sass/modules/_buttons.scss
src/sass/modules/_icons.scss

- For .btn--icon remove the opacity 0.8 because we have hover states
- Replace all asset control icons, including compare and exit
- Update css styles according to Kelsey

AIR-2419 (Design Refine: Fix asset control icons)

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/shared/datatypes/asset.interface.ts
src/app/shared/datatypes/collection-type-handler.ts
src/sass/modules/_metadata.scss
tslint.json

This PR includes logic for display of collection links, based on multiple types. on the asset page.
- Adds `collectionsLinks` member to `Asset` type, which is an array of `CollectionLink` types.
- Simplifies metadata loop for collection links by looping over `asset.collectionLinks`
- `mapCollectionLinks` called in asset page component, defines asset.collectionLinks

2467 Refactor - Collection Link Refactor

---

src/assets/i18n/en.json

Updates the privacy policy link in the footer to point to `https://www.ithaka.org/privacypolicy`

AIR-2478: Update privacy policy links

---

src/app/shared/tour/tour.component.pug
src/app/shared/tour/tour.component.ts

The `We've made some updates to groups!` modal has been enhanced to ensure tabbing to its different elements remains scoped to only the modal (not leaking out to the rest of the page). The approach taken in this PR is similar to that of the the `pwd-reset-component`.
Other Changes:
- Pressing escape at anytime will close the modal and give the original link element focus again.

AIR-2436: Fix tabbing on the image group help window

---

src/app/app.component.ts
src/sass/app.scss

The zendesk chat widget sometimes takes a second to load. This race condition can sometimes cause the widget to end up on a page it is not supposed to. Consider the steps to reproduce:
1. User visits login page (the widget should be displayed here)
2. We start fetching the zendesk chat widget script
3. The user quickly navigates away from the login page (assume it a page the widget should NOT appear)
4. The zendesk chat widget is finally ready to be displayed, so it happily displays even though it is for the wrong page.
**Solution:**
Leverage the zendesk chat api to determine when the widget is actually done loading. That way we can further determine if the current url is one it should be displaying on. Reference: https://api.zopim.com/files/meshim/widget/controllers/LiveChatAPI-js.html …

AIR-2470: Prevent chat widget from displaying on wrong pages

---

src/app/asset-page/asset-page.component.ts
src/app/asset-page/licenses.ts

Since implementing the CC icons/links under AIR-2270, the controlled list of license names for Creative Commons have slightly changed in Forum. This has caused an issue on the front end since we are no longer matching on our expected string.
Here are some examples:
https://stage.artstor.org/#/asset/1002989035
https://stage.artstor.org/#/asset/1003307364
Here is an example of what we should expect the `License` metadata field to look like when it is for CC:

AIR-2381: Fix Creative Common License icons/links

---

package.json
yarn.lock

We discovered an issue with OpenSeadragon that prevented reference strip thumbnails from loading due to missing headers. The fix was only a couple lines in the OpenSeadragon source. However, since the original OpenSeadragon project is seldom released, we decided to fork the repo so we can be more in control.
Check out the fix here in our forked repo: https://github.com/ithaka/openseadragon/pull/1
This PR simply points our dependency at this forked repo. This includes the ajax header fix above, however it also includes all changes made to the original OpenSeadragon project since `v2.4.0` (our current version). Testing manually, things still seem to be working, but let me know if you have any concerns.  See: https://github.com/openseadragon/openseadragon/releases

Update dependency to use our forked repo of openseadragon

---

package.json
src/app/_services/assets.service.ts
src/app/_services/group.service.ts
src/app/modals/add-to-group/add-to-group.component.pug
src/app/modals/add-to-group/add-to-group.component.ts
src/app/modals/new-ig-modal/new-ig-modal.component.ts

Resolves [PLATO-192](https://jira.jstor.org/browse/PLATO-192)
In PLATO-165 we introduced some logic to the 'Add to Group' modal that increased the complexity. We are taking an opportunity here to consolidate that logic to reduce the risk of edge cases while slightly boosting performance.
The diff here in github is kinda narly and unhelpful. Might recommend pulling down the code because a couple functions have been written from scratch.

PLATO-165-192: Refactor logic that retrieves image groups for 'Add To Group' modal

---

src/app/asset-page/asset-page.component.pug

- Minor whitespace changes automatically fixed by my IDE
- Remove the `lowercase` filter on the license field as it is causing a license to erroneously get sentenced cased.

Fix casing for license field

---

src/app/_services/auth.service.ts

Fixes the interval at which we refresh a user's session. It was intended to be 15 minutes, but configured for 15 hours.

PLATO-278: Fix interval for session refresh

---

src/app/app.component.ts
src/app/white-label-config.ts

Created an array of strings containing only the anchor/hash part of the url in the SPA. Checked the url hash fragment against the list and would show/load the chat widget by displaying/undisplaying the iFrame.
Small simplification and refactor of the solution.

PLATO-238: Constrained Zendesk chat widget to specific urls only

---

src/app/_services/asset-search.service.ts
src/app/_services/log.service.ts
src/app/asset-page/asset-page.component.ts

The ab_segment from the request will be sent to the Captains log as part of the artstor_item_view event

SRCHX-150: artstor_item_view events are missing some fields

---

src/app/_services/asset-search.service.ts

Resolves PLATO-354
Steps to reproduce:
- Navigate directly to asset: https://library.artstor.org/#/asset/ABROOKLYNIG_10312350495;prevRouteTS=1573050245273;iap=true
- Try download the image. Also notice the share url is blank
Issue is that when you navigate directly to an asset we don't have the ab segments data and this line blows up because `abSegments` is `undefined`: https://github.com/ithaka/aiw-ui/blob/684ab92ca47a5380c9dff82632850951f6d1343c/src/app/asset-page/asset-page.component.ts#L516

PLATO-354: Fix bug that prevent image download when navigating directly to an image url

---

src/app/_services/asset-search.service.ts

Adjustment to the fix applied in https://github.com/ithaka/aiw-ui/commit/430852c6d2e0e2fd5b5d6e773cfeaebecb3d33da
Reinitializes the abSegments map on each search request so it does not grow uncontrollably.

PLATO-354: Reinitialize abSegments map on each request

---

src/app/login-form/login-form.component.pug
src/app/login/login.component.pug

https://jira.jstor.org/browse/PALS-106
Apply aria-live attributes to Login error messages so screen readers announce them.

PALS-106: Login Page: Error Messages Aren't Announced via Screen Reader

---

src/app/collection-badge/collection-badge.component.pug

PLATO-312
Make tooltips fully visible in results instead of hiding behind adjacent images.
Have you written any necessary unit tests?
☐ Yes
☐ Not yet
☑︎ Not applicable
Have you added or updated any necessary integration tests?
☐ Yes
☐ Not yet
☑︎ Not applicable
Browsers tested on:
☑︎ Chrome
☐ Mobile
☐ Safari
☐ Mobile
☐ Firefox
☐ Mobile
☐ Edge
☐ IE11
☐ Not applicable

PLATO 312: Fix tooltip popping up behind results

---

package.json
yarn.lock

Using the latest forked version of openseadragon that uses the IIIF 2.0 standard for getting full size images.

PLATO-371: Update openseadragon dependencies

---

package.json
src/app/_services/image-group.service.ts
src/app/asset-page/agree-modal/agree-modal.component.ts
src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts
src/app/image-group-page/image-group-page.component.ts
src/app/image-group-page/terms-and-conditions/terms-and-conditions.component.ts
src/app/modals/loading-state/loading-state.component.ts
src/assets/i18n/en.json

Resolves [PLATO-364](https://jira.jstor.org/browse/PLATO-364)
The `artstor_download_single_image` event is currently logged on backend `artstor-download-service` when user downloads image or detail zoom.
After discussing with STORK, we will be moving the logging to the front end in order to move forward with the C5 work. Once these changes go out, we have a story to remove the logging from the service (See [PLATO-366](https://github.com/ithaka/artstor-download-service/pull/121))
This PR adds front end logging for the following events and :
- `artstor_download_single_image`
- `artstor_image_download_view`

PLATO-364: Add logging on front end for downloading images

---

src/app/_services/log.service.ts
src/app/asset-page/asset-page.component.ts

The artstor-log-service expects an array of dois, also moved it as a top level key after coordinating with blueprint team

PLATO-391: Pass doi as array

---

src/app/_services/asset-search.service.ts
src/app/_services/assets.service.ts
src/app/asset-filters/asset-filters.component.ts
src/app/modals/search-modal/search-modal.component.ts
src/app/modals/search-modal/search-query.ts

Allows users to filter in advanced search by only 1 date filter, whether start or end.
Implements same functionality as side bar in browse page.

SRCHX-138: Allow only one date filter on advanced search

---

src/app/modals/share-ig-link/share-ig-link.component.ts

Replace '%20' in group share tokens with '%2b' so that the tokens will be usable. (On some browsers, encodeURIComponent is converting + characters in the group share tokens to '%20' instead of '%2b'.)

PLATO-404: prevent share links with '%20'

---

src/app/asset-page/asset-page.component.ts

While recently debugging some artstor logging issues, we came across some interesting url parameters that affect can affect the way access is evaluated when viewing/downloading an asset. It would have been super helpful to have seen this url reflected in the logs in order to help draw conclusions. 
This PR just adds the full url to the asset related logging (viewing/downloading). Let me know if there are any concerns with this!

PLATO-423: Log the current url for asset related actions

---

src/app/asset-page/asset-page.component.ts

Resolves PLATO-463
Changes:
- Data platform requested that we be a little more granular with our `reason_for_authorization` field. This will help for account for the edge cases that allow a user to view an image even though they don't technically have the entitlements to do so.
- We learned that the asset page is server side rendered if it is hit with the `/public` or `/object` urls. https://github.com/ithaka/aiw-ui/blob/884259db16fc0eb967f7ac819e81286c5c4cc078/server/server.ts#L101 This running node server was actually emitting a captains log in an attempt to pre-render the page. This log was incomplete and overall not C5 worthy. A log would then again be fired on the front end when the javascript would run in the actual browser. The log generated at this stage is well formed. So here we …

PLATO-463: Artstor logging adjustments for view/download item events

---

src/app/asset-page/artstor-viewer/artstor-viewer.component.html

PLATO-219 and PLATO-226: Add aria labels to ImageViewer buttons so screen-readers can announce something in addition to "button."

PLATO-219 & 226: add aria labels to ImageViewer buttons.

---

src/app/_services/auth.service.ts
src/app/shared/idle-watcher.ts

Resolves PALS-136: user idle timeout issue
Whenever the user is idle for more than 90 minutes, we will logout the user by expiring the session.

PALS-136: Activate User Idle timeout functionality in Artstor

---

src/app/_services/asset-search.service.ts
src/app/asset-filters/asset-filters.component.ts
src/app/modals/search-modal/search-modal.component.ts
src/app/modals/search-modal/search-query.ts

Geographic queries will use the efq (encoded filter query) values from the search service. These values will be selected in the search results page.
The `SearchModal.loadAppliedFiltersFromURL()` method will parse the geography portion of the url to select the proper tree nodes.
This work has not been comprehensively tested. I only have one day left on this project (contract expires) and there are a lot of devs out of the office now so you folks will need to take this over the finish line.

SRCHX-392: Geographic filters in advanced search is using efq values

---

src/app/browse-page/card-view/card-view.component.pug
src/app/browse-page/card-view/card-view.component.scss

PLATO-207: On the Browse Groups page, the group tag elements do not appear to be interactive until they are hovered over. These elements need to have some indication (other than hover state changing their appearance) that they are interactive. Have added `1px solid #cfcfcf` border around tags.

PLATO-207: Make group tags appear clickable on Browse Groups page

---

src/app/app.component.ts
src/app/asset-page/asset-page.component.ts
src/app/shared/group-title/group-title.component.ts

Resolves [PLATO-227](https://jira.jstor.org/browse/PLATO-227)
Fixing error generated when asset may not have been loaded by the time we want to use it for the screenreader message.

PLATO-227: Fix screenreader message error on group presentation mode

---

src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.scss
src/app/asset-pp-page/asset-pp-page.component.pug

Found a couple issues after running our accessibility compliance gem on the artstor asset page.
Issues fixed:
1. Duplicated `assetpage-btn` ids - Just converted this over to using a class instead
2. Duplicated ids when a metadata field contained more than one value - For example, if a particular image had two `Subjects` of `Dolls` and `Doll Clothes`. We would display both of those values each with an `id` of ` subjects`. The solution here is to just convert to using a different attribute called `data-qa-id`.

PLATO-495: Accessibility fixes for asset page

---

src/app/asset-page/asset-page.component.pug

Removes the `aria-labelledby` attribute on the metadata values as they weren't really being used correctly, and it was causing failures using our accessibility gem. Discussed this with change with Florence too.

PLATO-495: Remove aria-labelledby attribute on metadata fields

---

package.json
src/app/login/login.component.pug

Resolves PALS-98
1. Artstor Login Page Lacks 1st Level Heading for Designation
2. As a user, I want to know what content I am looking at and where I am within the site without searching for this information so that I don't feel lost, confused, or frustrated.

PALS-98: Make Login heading H1

---

src/app/_services/auth.service.ts

Resolves PALS-213
Even after user logs out, Artstor watches idle time and triggers session expired modal dialog. PALS-213 resolves it. Artstor doesn't watch idle time of the user anymore after log out.

PALS-213: Don't track user idle time after log out

---

src/app/asset-grid/asset-grid.component.pug
src/app/asset-grid/asset-grid.component.ts

Personal Collection items do have `date` fields to sort by. Removing the option from the available sortable choices for the personal collection page only.

PLATO-510: Omit Date option from Sort on Personal Collection page

---

src/app/shared/pagination/pagination.component.scss

The PR ensures that we show the outline for the pagination control once it gains focus.

SRCHX-429: Show outline on showdow for pagination controls

---

src/app/modals/add-to-group/add-to-group.component.pug
src/app/modals/add-to-group/add-to-group.component.scss
src/app/modals/add-to-group/add-to-group.component.ts
src/app/modals/new-ig-modal/new-ig-modal.component.pug
src/app/modals/share-ig-link/share-ig-link.component.pug
src/app/modals/share-link-modal/share-link-modal.component.pug
src/app/modals/share-link-modal/share-link-modal.component.ts
src/app/uploader/uploader.component.pug
src/app/uploader/uploader.component.scss
src/sass/app.scss
src/sass/modules/_modals.scss

Resolves PLATO-206
There are currently two types of "help" links that can appear in modals across Artstor. 
1) Text based links:
2) Icon based links
Some of the styles were duplicated and others were colliding with eachother. To help clean things up I moved the two different styles to the top level scss file, and created new classes `help-link-text` and `help-link-icon` for referencing them.
This PR also ensures we are meeting the accessibility requirements outlined in PLATO-206

PLATO-206: Clean up help link/icon css rules and enhance for better accessibility

---

src/app/asset-grid/thumbnail/thumbnail.component.pug

Resolves [PLATO-496](https://jira.jstor.org/browse/PLATO-496)
To pass accessibility, we are giving titles to the icons on the asset thumbnails in the image group. 

PLATO-496: Reformatting badge icons in AIW asset group thumbnails

---

src/app/asset-page/asset-page.component.pug
src/app/modals/login-req-modal/login-req-modal.component.pug
src/app/modals/login-req-modal/login-req-modal.component.ts
src/app/modals/search-modal/search-modal.component.pug
src/app/search-page/search-page.component.pug
src/assets/i18n/en.json

Resolves [SRCHX-244](https://jira.jstor.org/browse/SRCHX-244)
Resolves [SRCHX-248](https://jira.jstor.org/browse/SRCHX-248)
Resolves [SRCHX-496](https://jira.jstor.org/browse/SRCHX-496)
A couple changes here... it's a nice read.
-  First ticket: Download and Add to Image group buttons on the asset page were not keyboard interactive. This had to do with the focus on the please login modal that shows up when they are not logged in. 
- Second ticket: Needed to add an aria label to the alert in advanced search so that the screen reader announces the error when it appear in the modal when the user enters a end date less than a start date.
- Third ticket: Removed a useless div around the screen reader only elements that allow the user to switch between filter section and search result section …

SRCHX-2444-248-496: Multiple AIW Accessibility fixes

---

src/app/modals/search-modal/search-modal.component.pug
src/app/modals/search-modal/search-modal.component.scss
src/app/modals/search-modal/search-modal.component.ts

Resolves [SRCHX-137](https://jira.jstor.org/browse/SRCHX-137)
In the advanced search modal, there are a LOTTTT of filters and scrolling through all of them with a tab is ridiculous. So we added the ability to skip to the next filter entirely like we do on the search results page between filters and results. 
The logic will create a shortcut to the next filter, and on the last filter create a shortcut to the search button.
There is also some heading changes for accessibility with style changes so they don't actually appear different than they did before.

SRCHX-137: Allow skipping of large sections in Advanced Search

---

package.json
src/app/browse-page/browse-page.component.pug
src/app/browse-page/browse-page.component.scss
src/app/browse-page/library.component.pug
src/app/browse-page/library.component.ts
src/app/home/featured/featured.component.pug
src/app/home/featured/featured.component.scss
src/app/home/featured/featured.component.ts
src/app/home/home.component.pug
src/app/home/home.component.scss

Resolves [SRCHX-447](https://jira.jstor.org/browse/SRCHX-447)
Resolves [SRCHX-448](https://jira.jstor.org/browse/SRCHX-448)
Resolves [SRCHX-247](https://jira.jstor.org/browse/SRCHX-247)
More multiple accessibility fixes to the Artstor website.
**SRCHX-447 (Browse Page)**
- add discernable text to buttons, hidden on page
- remove duplicate and unused id (main-content)
- **FIXED** the alert message when filtering when no text entered
**SRCHX-448 (Home Page)**
- remove duplicate ids since they must be unique from the featured cards, used data-qa instead
- links must have discernable text, hidden on the page
- `<ul>` tags must only contain `<li>`, added a no-bullets class with styling 
**SRCHX-247 (Home Page slideshow)**
- removed the auto-cycling to avoid confusion and accessibility problems …

SRCHX-447-448-247: 

---

src/app/browse-page/library.component.pug
src/app/home/featured/featured.component.pug

Resolves [SRCHX-447](https://jira.jstor.org/browse/SRCHX-447)
Resolves [SRCHX-448](https://jira.jstor.org/browse/SRCHX-448)
Accessibility tickets are fun. 
Needed role's to be list and list item, otherwise even though a `<li>` was wrapped by a `<ul>`, accessibility tools thought it was not.
Also another ID that needed to be removed. Unused throughout the code and was creating duplicates

SRCHX-447-448: Better accessiblity fixes for browse and home page

---

src/app/_services/asset-search.service.ts

Resolves SRCHX-553
On the Duplicates and Details page, we want the items to be sorted by work sequence number in ascending order. This page has a clusterId, which was what we will use to trigger this sorting.

SRCHX-553: Sort by worksequence in Duplicates and Details

---

src/app/_services/flag.service.ts
src/app/asset-page/asset-page.component.pug
src/app/asset-page/asset-page.component.ts

PALS-294
If a user has access via an ADL Institution, let them download an image (after accepting T&Cs) without logging into an individual account.

PALS-294: AIW: Temporarily remove login-to-download requirement

---

src/app/asset-page/asset-page.component.scss
src/sass/modules/_forms.scss

on-behalf-of: @ithaka <robert.niznik@ithaka.org>
Resolves BLUE-193
Update contrast for dropdown items when hovered and focused so that they are WCAG AA and AAA compliant.

BLUE-193: Update dropdown item highlight contrast

---

src/app/asset-page/asset-page.component.ts

Resolves PALS-297
Explicitly set isLoggedIn to true or false so it does not evaluate to undefined

PALS-297: AIW: Turn log-in to download back on

---

src/app/shared/footer/footer.component.pug

Resolves BLUE-206
The Google "Select Language" select is overlapping text when viewport is 420px wide and text spacing is increased using this [tool](https://codepen.io/stevef/full/YLMqbo). Update column spacing classes to fix this.

BLUE-206: Update footer columns spacing for smaller viewports

---

src/app/shared/footer/footer.component.pug

Resolves BLUE-206
After UX review, it was determined that we should support at least 320px wide views. The Google Select Language section is separated out from the disclaimer section to avoid competing for space.

BLUE-206: Divide out bottom sections

---

src/sass/modules/_buttons.scss

Resolves PLATO-605
WCAG states that there should be accommodations for tools that change the natural line height, text spacing, etc. When applying these changes, the buttons on the image page were getting cut off.
BEFORE:
Setting a `min-height` instead now to not restrict the height, should the button text need to wrap. 
AFTER:

PLATO-605: Allows buttons to grow in height when needed

---

src/app/category-page/category-page.component.pug
src/app/category-page/category-page.component.scss
src/app/category-page/category-page.component.ts
src/app/collection-page/collection-page.component.pug
src/app/collection-page/collection-page.component.scss
src/app/collection-page/collection-page.component.ts
src/app/modals/search-modal/search-modal.component.scss
src/app/nav-menu/nav-menu.component.pug
src/app/search-page/search-page.component.pug
src/app/search-page/search-page.component.scss
src/app/search-page/search-page.component.ts
src/app/shared/search/search.component.scss

Resolves BLUE-205
Previously links to Register and Advanced Search were not available on mobile, as well as the ability to use filters. These changes allow for that functionality to be available.

BLUE-205: Make links and filters accessible on mobile

---

src/app/category-page/category-page.component.ts
src/app/collection-page/collection-page.component.ts
src/app/search-page/search-page.component.ts

Resolves BLUE-205
Need to make showFilters public to allow use in templates.

BLUE-205: Allow showFilters to be used in template

---

package.json
src/polyfills.ts
yarn.lock

Resolves BLUE-210
Deployment of BLUE-210 failed. Upon inspecting the codebase I realized the JavaScript is being compiled to es5. As a result, we need to also include the [es5 custom elements adapter](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs#custom-elements-es5-adapterjs) to have things running properly with the web component polyfills.

BLUE-210: Add es5 adapter polyfill

---

server/server.ts

Resolves BLUE-210
When trying to serve the built SSR build, node would fail with `ReferenceError: Document is not defined at eval (webpack:///./node_modules/lit-element/lib/css-tag.js?:16:62)`. At first I believed this might relate to using ES6 dependencies such as `lit-element` and `lit-html` and needing to exclude them from the server build. Alas, the error was simply a result of the server not having `Document` defined and nothing to do with the dependency referencing it. So I updated the server global to include `Document`.

BLUE-210: Add global Document to server

---

src/app/nav-menu/nav-menu.component.scss
src/app/shared/nav/nav.component.pug
src/app/shared/nav/nav.component.scss

Resolves BLUE-210
Previously I had tweaked the z-index values of the navbar to allow visibility of Pharos tooltips which resulted in issues for the group view. This simply ups the z-index of the tooltip itself and leaves the current AIW z-index setup alone.

BLUE-210: Fix z-index usage

---

src/app/browse-page/card-view/card-view.component.pug
src/app/browse-page/card-view/card-view.component.scss

Resolves SRCHX-573
Ran into a visual issue when the screen is less wide, the titles that are single word and very long do not wrap causing a very difficult viewing experience for a user. This small styling change should eleviate that.

SRCHX-573: Wrap text for group-browse Titles for smaller screens

---

src/index.html
src/polyfills.ts

Load the web component polyfills from <head> in the index.html file as they may be loading too late from `polyfills.ts`.

Load web component polyfills from index.html

---

src/app/asset-grid/asset-grid.component.pug
src/app/modals/search-modal/search-modal.component.pug

Resolves SRCHX-574
Resolves SRCHX-576
Adding accessibility features (screen reader announce) error message when there are no search results and when there is an error using advanced search modal on ARTSTOR

SRCHX-574-576: Add alert role to error messages for screen readers

---

angular.json
babel.config.js
browserslist
custom-webpack.config.js
package.json
src/app/app.module.ts
src/app/shared/datatypes/collection-type-handler.ts
src/main.ts
src/polyfills.ts
yarn.lock

Resolves BLUE-260
Angular (the cli specifically) expects your dependencies to be available in ES5 format if you intend on supporting IE11. The fun thing is they don't provide a way for you to transpile dependencies yourself in instances where the library is not available in ES5. Luckily there is a [tool](https://www.npmjs.com/package/@angular-builders/custom-webpack) that allows us to use custom webpack configs along with the cli. Also had to move where the web component polyfills were being applied as they were conflicting with the other polyfills AIW is using.

BLUE-260: Support web components in IE11

---

src/app/asset-filters/asset-filters.component.scss

Resolves SRCHX-577
When a user has a zoomed in view, the date filter on the asset page was unreadable. Styling has been added to adjust how it appears when the user is zoomed in or on a mobile device. Now the button's text is always readable and appears cleanly to the user. 
Regular:
Zoomed in:

SRCHX-577: Adjust styling on date filter when zoomed in

---

src/app/asset-grid/thumbnail/thumbnail.component.pug
src/app/asset-page/artstor-viewer/artstor-viewer.component.html

Resolves BLUE-254
Removes breaks found in tooltip content as these are not desired with the use of Pharos tooltips.

BLUE-254: Remove breaks from tooltip content

---

src/app/asset-page/asset-page.component.pug

Resolves  PLATO-890
Fixes terms and conditions link on the asset page

PLATO-890: Fix Artstor terms and condition link

---

src/app/white-label-config.ts
src/assets/i18n/en.json

Resolves BLUE-347
Adds a link to Artstor LibGuides to the footer

BLUE-347: Add Artstor LibGuides to footer

---

src/app/asset-page/licenses.ts

Resolves PLATO-1036
Changes image and URL for Creative Commons: Public Domain Mark

PLATO-1036: change image and URL for Creative Commons: Public Domain Mark

---

Dockerfile

Resolves PALS-744
In this PR, we made a change to Docker base image to point to Artifactory instead of Docker Hub.

PALS-744: Update docker image reference to point to Artifactory instead of Docker Hub

---

src/app/asset-filters/asset-filters.component.ts

Resolves SRCHX-1142
Changes in this PR are meant to fix a reported prod bug related to filter selection. Apparently the filter selection caused an uncaught error on the UI side where we were trying to split a parsed array by `,`. This prevented the retention of updated search term in the filters component and causing unexpected search behavior on the UI side.

SRCHX-1142: Filter selection bug fix

---

src/app/asset-page/asset-page.component.pug
src/app/collection-badge/collection-badge.component.pug
src/sass/modules/_viewer.scss

Resolves PLATO-1561
* Fixes tab ordering of focusable elements so that image gets focus before the metadata (top-down, left-right is more natural)
* Remove focus from elements that are invisible
* Put a little space around the image so you can tell the image is focused

PLATO-1561: AIW accessibility fixes

---

src/index.html

Remove the existing GDPR banner so we can go live with OneTrust.

Remove old GDPR banner

---

src/app/search-page/search-page.component.ts

Resolves SRCHX-1203
In SRCHX-1203 added a link to allow ARTSTOR users run the same search on JSTOR. While viewing GA data realized there's another JSTOR search URL from AIW and adding this will make it easier to track it in GA and distinguish clicks.

SRCHX-1203: Add URL param to track clicks on JSTOR GA

---

src/app/search-page/search-page.component.ts

Resolves SRCHX-1286
Changes in this PR ensure that the section skip links on search page (i.e. Skip to Search Section & Skip to Filter Section) are not buggy and change the active focus to the relevant sections without jumping back and forth.

SRCHX-1286: Increase timeout for search skip section links

---

package.json

Resolves PLATO-2520
Update Openseadragon to the latest version in order to fix a bug on production.

PLATO-2520: Update Openseadragon version

---

src/app/_services/account.service.ts
src/app/_services/auth.service.ts
src/app/modals/aji-intercept/aji.component.pug
src/app/modals/aji-intercept/aji.component.scss
src/app/modals/aji-intercept/aji.component.ts
src/app/post-login-banner/drop-banner/drop-banner.component.pug
src/app/post-login-banner/drop-banner/drop-banner.component.scss
src/app/post-login-banner/static-banner/static-banner.component.pug

Resolves PALS-1534
- Update logic for displaying AJI intercept and post login banner to targeted users
- Add data-sc attributes for GA tracking
AJI Intercept
Post-login drop down banner
Link behavior on hover

PALS-1534: Update the Artstor AJI Modal/Banner with copy, and a list of users to roll out to
